"""Controller configuration constants."""

DEFAULT_WINDOW_WIDTH = 1000
DEFAULT_WINDOW_HEIGHT = 700
DEFAULT_GRID_WIDTH = 20
DEFAULT_GRID_HEIGHT = 20
DEFAULT_AGENTS_PER_REGION = 3
DEFAULT_FPS = 30
STEP_INTERVAL_MS = [500, 200, 100, 50, 20]
SPEED_LABELS = ["Slow", "Normal", "Fast", "Faster", "Max"]
SIDEBAR_WIDTH = 280
RESULTS_DIR = "results"
