MIN_ENERGY_TO_REPRODUCE_LOW = 40
MIN_ENERGY_TO_REPRODUCE_HIGH = 80

IDEAL_TEMPERATURE_LOW = 0
IDEAL_TEMPERATURE_HIGH = 28

TEMPERATURE_TOLERANCE_LOW = 4
TEMPERATURE_TOLERANCE_HIGH = 10

METABOLIC_RATE_LOW = 10
METABOLIC_RATE_HIGH = 30

MATURITY_AGE_LOW = 20
MATURITY_AGE_HIGH = 40

SIZE_LOW = 20
SIZE_HIGH = 60

BREEDING_INTERVAL_LOW = 2
BREEDING_INTERVAL_HIGH = 20
